language: java
jdk: openjdk8
install: true

addons:
  sonarcloud:
    organization: "wimdeblauwe-github"
    token:
      secure: "gdJLA9IWO0TKGmg4yAHL2dcvfqTHgFbwJ76K8H5BtqhadhKQisSnqV/5w0Ee1B5lD4YclzoywwLHGYbwFVzVyiqri2+CGX90CYI3v2XIplO2tiPEtHDQYFN7vC+j1u8MgIIWnJqKvSE2GIXgBBxmvdMdgkJ2eRVyvMf6JNuNbfw24asS9OEH2TGMnz2PhtvD2ZHK6FlAUzhNgJIfK3d57Jix0m2E09C1fqyNzKT47YRrCb4PJejYU9PXrbONds6Ti65GMRJaZOIEXqqHOJpOmANFmLVN7t+HRCZsryew0YbRwbBqrpmmDdolthvP0Lhya2GG1C33wxjxPyKoYKzSzItNNzKhEt3HU7rpG3djXwxnFEKvdCrE5xco+gQd0xEV8sZilCsIElW2yTNMbD2+G1HQNwZO2RlVnxxwZLsmbu9YwMeelJ4od9kZmGvCghvWx72qLsmDCa2tam1Cn5sGShBM3xczDfhb3AB5gg/Z+Khq1+l619gviQr6KosDX0B61sWuo4W2/voI6XMjZci5yEhosLolm6LmW+8gMAdtzSN+HMIVG7PcT/9hsMD7ntUrz8Mo1Ut5LOZI7m0qK7XDs/I0YburpTdIAA10NunAMI9G+wxqlLOrjZQmuIUAg453W25Fuyk98unZH3GqJC/+9IrgNGz0It1vYbeJ3p63IX4="
    branches:
      - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean install sonar:sonar